//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTickerSparklines.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTickerSparklines.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label row of internal resource {0} is invalid.{3}    Expected value = {1}{3}    Actual value   = {2}.
        /// </summary>
        internal static string ERRMSG_CORRUPTED_EMBBEDDED_RESOURCE_LABEL {
            get {
                return ResourceManager.GetString("ERRMSG_CORRUPTED_EMBBEDDED_RESOURCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail record {0} of internal resource {1} is invalid.{5}    Expected field count = {2}{5}    Actual field count   = {3}{5}    Actual record        = {4}.
        /// </summary>
        internal static string ERRMSG_CORRUPTED_EMBEDDED_RESOURCE_DETAIL {
            get {
                return ResourceManager.GetString("ERRMSG_CORRUPTED_EMBEDDED_RESOURCE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quote Server Error: Message     = {0}{3}                          Endpoint    = {1}{3}                          QueryString = {2}.
        /// </summary>
        internal static string ERRMSG_SERVER_ERROR_REPORT {
            get {
                return ResourceManager.GetString("ERRMSG_SERVER_ERROR_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} Exception arose. Details follow.{5}{5}                        Message             = {1}{5}                        TargetSite (Method) = {2}{5}                        Source (Assembly)   = {3}{5}                        StackTrace          = {4}.
        /// </summary>
        internal static string ERRMSG_WINMAIN_EXCEPTION {
            get {
                return ResourceManager.GetString("ERRMSG_WINMAIN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order = {0}, Label = {1}.
        /// </summary>
        internal static string SYMBOLINFO_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("SYMBOLINFO_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function = {0}, Parameter = {1}.
        /// </summary>
        internal static string TPL_API_FUNCTION_MAP_TOSTRING {
            get {
                return ResourceManager.GetString("TPL_API_FUNCTION_MAP_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _1symbol (Symbol) = {0}, _2name (Name) = {1}, _3type (Type) = {2}, _4region (Region) = {3}, _5marketOpen (Market Opening Time) = {4}, _6marketClose (Market Closing Time) = {5}, _7timezone (Time Zone) = {6}, _8currency (Currency) = {7}, __9matchScore (Match Score) = {8}.
        /// </summary>
        internal static string TPL_BESTMATCH_TOSTRING {
            get {
                return ResourceManager.GetString("TPL_BESTMATCH_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL ERROR 001: Internal field counter intColIndex has an invalid value of {0}. Its value must always be less than {1}..
        /// </summary>
        internal static string TPL_INTERNAL_ERROR_001 {
            get {
                return ResourceManager.GetString("TPL_INTERNAL_ERROR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol = {0}, Issuer Name = {1}, Selected {2}.
        /// </summary>
        internal static string TPL_TICKER_SYMBOL_TOSTRING {
            get {
                return ResourceManager.GetString("TPL_TICKER_SYMBOL_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        internal static string XLS_R1_C1_LABEL {
            get {
                return ResourceManager.GetString("XLS_R1_C1_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string XLS_ROW_DISP_DISCARD {
            get {
                return ResourceManager.GetString("XLS_ROW_DISP_DISCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        internal static string XLS_ROW_DISP_KEEP {
            get {
                return ResourceManager.GetString("XLS_ROW_DISP_KEEP", resourceCulture);
            }
        }
    }
}
